require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "tmp/**/*"
    - ".git/**/*"
    - "bin/*"
    - "db/**/*"
  TargetRubyVersion: 3.1
  SuggestExtensions: false

  DisabledByDefault: true

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - "config/**/*"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
