require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "tmp/**/*"
    - ".git/**/*"
    - "bin/*"
    - "db/**/*"
  TargetRubyVersion: 3.1
  SuggestExtensions: false

Metrics:
  Enabled: false

#Metrics/BlockLength:
#  Exclude:
#    - "config/**/*"
#
#Metrics/MethodLength:
#  Max: 20

Naming/VariableNumber:
  EnforcedStyle: snake_case

Rails/Delegate:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

RSpec/BeEq:
  Enabled: false

RSpec/EmptyLineAfterFinalLet:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FrozenStringLiteralComment:
  Exclude:
    - "config/**/*"

Style/HashSyntax:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
